### ISSUE TITLE
should we leave JSON as a valid "language"

### ISSUE THREAD

**Issue by mackenza** [vlucas/devdata.io#8]
I know we converted the former `JSON` to `Javascript` based on the feedback you got from red-cesspit, and I agree with the logic, but I think having the raw JSON as a "language" is still valid. The use case is I want to copy/paste the contents directly into a new file like `states.json` rather than use it as a .js file.

**Comment by vlucas** [comment]
Yes, it is still valid. I actually already updated the website API to return it with the latest commit:
http://devdata.io/datasets/states?lang=json

I just have not added it to the UI yet, because frankly I am not sure how. Should I just leave it as a raw API, or should I stringify the JSON to display it in that text box like the others? Seems like JSON could go either way.

**Comment by mackenza** [comment]
yeah, I noticed I could use it as an API, which is good as I still am getting to my plans around DevData-cli ;)

I was thinking you should output to a textbox and call the tab `JSON` or `raw JSON`... just don't get rid of the API

**Comment by vlucas** [comment]
So... here's a crazy thought. I am thinking about moving the API to ONLY return JSON, and moving all the formatting JavaScript to the frontend instead of it being formatted on the backend. It's a nice option to have since it's all JS :)

**Comment by mackenza** [comment]
how very SPA of you ;)
